# Generated by Django 3.0.4 on 2020-03-18 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='ab_id',
            field=models.IntegerField(unique=True),
        ),
    ]
