# Generated by Django 3.0.4 on 2020-03-18 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_auto_20200318_0432'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='bedroom_count',
            field=models.IntegerField(null=True),
        ),
    ]
